services:
    kinerity.postpm.listener:
        class: kinerity\postpm\event\listener
        arguments:
            - @auth
            - @template
            - @user
        tags:
            - { name: event.listener }
